import type { GalleryItem, SiteSettings } from "@/types";

export const siteSettingsData: SiteSettings = {
    siteName: "Mode Gallery",
    siteDescription:
        "Dual-theme portfolio showcasing tattoo artistry and creative works",
    studioName: "187 Tattoo Studio",
    socialLinks: {},
};

export const galleryItemsData: GalleryItem[] = [
    {
        slug: "angel-wings",
        mode: "tattoo",
        category: "black-grey",
        title: "Angel Wings Back Piece",
        image: "https://images.unsplash.com/photo-1578301978018-3005759f48f7?w=600&h=800&fit=crop",
        alt: "Large black and grey angel wings back tattoo",
        description: "Full back piece featuring detailed feathered angel wings",
        date: "2026-01-22T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "clock-piece",
        mode: "tattoo",
        category: "black-grey",
        title: "Pocket Watch",
        image: "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=600&h=800&fit=crop",
        alt: "Black and grey pocket watch tattoo",
        description: "Intricate vintage pocket watch with broken glass effect",
        date: "2026-02-03T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "portrait-woman",
        mode: "tattoo",
        category: "black-grey",
        title: "Woman Portrait",
        image: "https://images.unsplash.com/photo-1581883073146-d1d78bef8f8b?w=600&h=800&fit=crop",
        alt: "Black and grey woman portrait tattoo",
        description: "Soft shaded portrait with flowing hair and subtle details",
        date: "2026-01-15T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "sample-sleeve",
        mode: "tattoo",
        category: "black-grey",
        title: "Black & Grey Sleeve",
        image: "https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?w=600&h=800&fit=crop",
        alt: "Black and grey tattoo sleeve",
        description: "Full sleeve design in black and grey with smooth gradients",
        date: "2026-01-05T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "skull-roses",
        mode: "tattoo",
        category: "black-grey",
        title: "Skull & Roses",
        image: "https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?w=600&h=800&fit=crop",
        alt: "Black and grey skull with roses tattoo",
        description: "Detailed skull surrounded by elegant roses in smooth grey tones",
        date: "2026-02-12T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "dagger-rose",
        mode: "tattoo",
        category: "old-school",
        title: "Dagger & Rose",
        image: "https://images.unsplash.com/photo-1565058379802-bbe93b2f703a?w=600&h=800&fit=crop",
        alt: "Traditional dagger through rose tattoo",
        description: "Iconic dagger piercing a rose, bold lines and classic colors",
        date: "2026-01-25T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "panther-head",
        mode: "tattoo",
        category: "old-school",
        title: "Crawling Panther",
        image: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=600&h=800&fit=crop",
        alt: "Traditional crawling panther tattoo",
        description: "Fierce crawling panther in traditional American style",
        date: "2026-01-18T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "sailor-jerry-heart",
        mode: "tattoo",
        category: "old-school",
        title: "Sailor Heart",
        image: "https://images.unsplash.com/photo-1542856391-010fb87dcfed?w=600&h=800&fit=crop",
        alt: "Traditional sailor heart with banner tattoo",
        description: "Classic heart and banner design in true Sailor Jerry style",
        date: "2026-02-01T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "sample-anchor",
        mode: "tattoo",
        category: "old-school",
        title: "Traditional Anchor",
        image: "https://images.unsplash.com/photo-1590246815117-0b5bdabf8161?w=600&h=800&fit=crop",
        alt: "Traditional old school anchor tattoo",
        description:
            "Classic old school anchor design with bold lines and traditional coloring",
        date: "2026-01-10T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "swallow-birds",
        mode: "tattoo",
        category: "old-school",
        title: "Classic Swallows",
        image: "https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?w=600&h=800&fit=crop",
        alt: "Traditional swallow birds tattoo",
        description: "Pair of classic swallows with bold outlines and vibrant colors",
        date: "2026-02-08T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "eye-detail",
        mode: "tattoo",
        category: "realistic",
        title: "Hyper-Realistic Eye",
        image: "https://images.unsplash.com/photo-1494869042583-f6c911f04b4c?w=600&h=800&fit=crop&crop=faces",
        alt: "Hyper-realistic human eye tattoo",
        description: "Stunning eye tattoo with reflection details and natural coloring",
        date: "2026-02-05T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "lion-portrait",
        mode: "tattoo",
        category: "realistic",
        title: "Lion Portrait",
        image: "https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?w=600&h=800&fit=crop&crop=faces",
        alt: "Realistic lion portrait tattoo on arm",
        description: "Majestic lion portrait with incredible detail and lifelike shading",
        date: "2026-02-10T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "rose-hand",
        mode: "tattoo",
        category: "realistic",
        title: "Rose on Hand",
        image: "https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&h=800&fit=crop",
        alt: "Realistic rose tattoo on hand",
        description: "Delicate realistic rose with water droplets on petals",
        date: "2026-01-20T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "sample-portrait",
        mode: "tattoo",
        category: "realistic",
        title: "Portrait Realism",
        image: "https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?w=600&h=800&fit=crop",
        alt: "Realistic portrait tattoo example",
        description:
            "A detailed portrait tattoo showcasing realistic shading and detail work",
        date: "2026-01-15T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "wolf-moon",
        mode: "tattoo",
        category: "realistic",
        title: "Wolf & Moon",
        image: "https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=600&h=800&fit=crop&crop=faces",
        alt: "Realistic wolf howling at moon tattoo",
        description: "Detailed wolf portrait with atmospheric moonlit background",
        date: "2026-01-28T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "bomber-jacket",
        mode: "art",
        category: "clothes",
        title: "Custom Bomber Jacket",
        image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=600&fit=crop",
        alt: "Hand-painted bomber jacket with tiger design",
        description:
            "Vintage bomber jacket featuring a hand-painted Japanese tiger",
        date: "2026-02-09T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "hoodie-skull",
        mode: "art",
        category: "clothes",
        title: "Skull Hoodie",
        image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=600&fit=crop",
        alt: "Custom painted hoodie with skull design",
        description: "Black hoodie with detailed skull and floral artwork",
        date: "2026-02-02T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "leather-vest",
        mode: "art",
        category: "clothes",
        title: "Painted Leather Vest",
        image: "https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=600&h=600&fit=crop",
        alt: "Custom painted leather vest with eagle design",
        description: "Vintage leather vest with hand-painted American eagle",
        date: "2026-01-24T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "sample-jacket",
        mode: "art",
        category: "clothes",
        title: "Custom Denim Jacket",
        image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=600&fit=crop",
        alt: "Hand-painted denim jacket",
        description: "One-of-a-kind hand-painted denim jacket with unique artwork",
        date: "2026-01-20T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "tshirt-abstract",
        mode: "art",
        category: "clothes",
        title: "Abstract Tee",
        image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&h=600&fit=crop",
        alt: "T-shirt with abstract art print",
        description: "Limited edition t-shirt featuring original abstract artwork",
        date: "2026-01-16T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "nature-abstract",
        mode: "art",
        category: "paintings",
        title: "Nature's Chaos",
        image: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=600&h=600&fit=crop",
        alt: "Abstract nature inspired painting",
        description: "Organic forms and natural textures in earth tones",
        date: "2026-01-19T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "ocean-dreams",
        mode: "art",
        category: "paintings",
        title: "Ocean Dreams",
        image: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=600&h=600&fit=crop",
        alt: "Abstract ocean waves painting",
        description: "Fluid abstract piece capturing the movement of ocean waves",
        date: "2026-02-04T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "portrait-study",
        mode: "art",
        category: "paintings",
        title: "Portrait Study",
        image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=600&fit=crop",
        alt: "Contemporary portrait painting",
        description: "Mixed media portrait with expressive color palette",
        date: "2026-01-27T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "sample-abstract",
        mode: "art",
        category: "paintings",
        title: "Abstract Canvas",
        image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&h=600&fit=crop",
        alt: "Abstract painting on canvas",
        description:
            "Contemporary abstract piece with bold colors and dynamic composition",
        date: "2026-02-01T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "urban-sunset",
        mode: "art",
        category: "paintings",
        title: "Urban Sunset",
        image: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=600&h=600&fit=crop",
        alt: "Abstract urban sunset painting",
        description: "Vibrant cityscape at golden hour with bold brushstrokes",
        date: "2026-02-11T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "af1-graffiti",
        mode: "art",
        category: "shoes",
        title: "Graffiti Air Force 1s",
        image: "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=600&h=600&fit=crop",
        alt: "Custom Air Force 1 sneakers with graffiti art",
        description:
            "White AF1s transformed with colorful graffiti-style artwork",
        date: "2026-02-06T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "converse-portrait",
        mode: "art",
        category: "shoes",
        title: "Portrait Converse",
        image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&h=600&fit=crop",
        alt: "Custom Converse with portrait artwork",
        description:
            "High-top Converse featuring hand-painted celebrity portrait",
        date: "2026-01-21T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "jordan-custom",
        mode: "art",
        category: "shoes",
        title: "Custom Air Jordans",
        image: "https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=600&h=600&fit=crop",
        alt: "Custom painted Air Jordan sneakers",
        description: "Air Jordan 1s with hand-painted flame design",
        date: "2026-02-13T10:00:00.000Z",
        featured: true,
    },
    {
        slug: "sample-sneakers",
        mode: "art",
        category: "shoes",
        title: "Custom Sneakers",
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop",
        alt: "Custom painted sneakers",
        description: "Hand-painted custom sneakers featuring original artwork",
        date: "2026-01-25T10:00:00.000Z",
        featured: false,
    },
    {
        slug: "vans-skull",
        mode: "art",
        category: "shoes",
        title: "Skull Vans",
        image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f?w=600&h=600&fit=crop",
        alt: "Custom Vans with skull artwork",
        description: "Classic Vans Old Skools with detailed skull and roses",
        date: "2026-01-29T10:00:00.000Z",
        featured: true,
    },
];
